### ISSUE TITLE
Extensions will emit `getters['type-map/hasGraph'] is not a function` on their resource detail pages

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#15402]
**Describe the bug**
Extension detail pages fail to render. Introduced by https://github.com/rancher/dashboard/pull/15159.

**To Reproduce**
- Install the Elemental UI extension
- Visit one of the detail pages i.e. `/elemental/c/_/elemental.cattle.io.managedosversionchannel/fleet-default/sl-micro-6.1-base-channel`

**Result**
<img width="1126" height="513" alt="Image" src="https://github.com/user-attachments/assets/bcd134f4-c1fb-49a2-bfef-204d9f6c7e60" />

**Expected Result**
The page should render without error

<img width="1271" height="590" alt="Image" src="https://github.com/user-attachments/assets/4f79d2bc-03e2-417e-8fb6-73453a4bac20" />

**Screenshots**

**Additional context**
Extensions with detail pages effectively have a copy of @shell/ResourceDetail/index.vue which checks hasGraph. If they get built with a new shell they'll be fine but without it they'll break.

**Comment by izaac** [comment]
Low effort quick manual check to look any javascript exceptions around this fleet area.

**Comment by a-arias** [comment]
**TESTS**
Rancher : v2.13-69e9a6ff0ae940804e91c19e04cd158894dfad06-head

UI: master https://github.com/rancher/dashboard/commit/08df60cf828d73a3f6ad09497135bf442acbeb60

Fix validated ✅

https://github.com/user-attachments/assets/798df08d-ed54-4bad-ba1b-35da2ba0af0d
