### ISSUE TITLE
[BUG] Search not working

### ISSUE THREAD

**Issue by callmewhatuwant** [rancher/dashboard#15463]
**Rancher Server Setup**
- Rancher version: 2.12.1
- Installation option (Docker install/Helm Chart):
   - Helmchart: 2.12.1 RKE2 Version 1.32.4

- Cluster Type (Downstream):
   - only imported rke2 clusters with k8s version: 1.32.4 and higher

**User Information**
- What is the role of the user logged in? 
   - Admin

**Describe the bug**
The search function does not work anymore. When i go for example to pods and search for something nothing happens. I tried with multiple browsers and a clean cache. This happens after the update from 2.11.2

**Comment by callmewhatuwant** [comment]
Can i downgrade from 2.12.1 to 2.11.2 ? Does this work?

**Comment by skanakal** [comment]
@callmewhatuwant Did you install kubewarden UI extension? 
Also, can you share the console log while searching the pods list?

**Comment by callmewhatuwant** [comment]
@skanakal Why should I install the kubewarden UI extension ?? Do you mean rancher logs from the pods? I get no erros or logs while searching in the ui for a pod name.

**Comment by callmewhatuwant** [comment]
I found the root cause: the SUSE Observability extension was installed.
After uninstalling it, the search started working again.

Before removing the extension I consistently saw this error:

```
Uncaught (in promise) TypeError: e.startsWith is not a function
    at u.convertArrayPath (steve-pagination-utils.ts:279:14)
    at steve-pagination-utils.ts:530:31
    at c (reactivity.esm-bundler.js:861:19)
    at Array.map (<anonymous>)
    at G (reactivity.esm-bundler.js:869:27)
    at Proxy.map (reactivity.esm-bundler.js:793:12)
    at steve-pagination-utils.ts:503:12
    at Array.map (<anonymous>)
    at u.convertPaginationParams (steve-pagination-utils.ts:501:8)
    at u.createParamsForPagination (steve-pagination-utils.ts:426:28)
```

Could you explain why this happens?

**Comment by skanakal** [comment]
@callmewhatuwant 
It's duplicate of  https://github.com/rancher/dashboard/issues/15460

> Could you explain why this happens?


please follow this https://github.com/rancher/dashboard/issues/15460#issuecomment-3303129845

**Comment by richard-cox** [comment]
@callmewhatuwant can you confirm which Rancher UI Extensions you have installed?

**Comment by callmewhatuwant** [comment]
@richard-cox 
The root cause was the installed SUSE Observability extension. After removing it the search function is working again

**Comment by richard-cox** [comment]
Closing, fixed in 2.12.2 and 2.13, same root issue as https://github.com/rancher/dashboard/issues/15460
