### ISSUE TITLE
Growlmanager Storybook breaks

### ISSUE THREAD

**Issue by scures** [rancher/dashboard#7608]
After merging rancher/dashboard#7451, seems that the store broke.

```
Object.assign(...).registerModule is not a function
```

Maybe a good solution would be to continue with the unified store until we remove the store dependency for the component.

**Comment by catherineluse** [comment]
If it's merged, I'd say you should remove the to triage label and add the review label
